version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-nested-layer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1s0whq9cze40u"
s3_prefix = "sam-nested-layer"
region = "us-west-2"
capabilities = ["CAPABILITY_IAM","CAPABILITY_AUTO_EXPAND"]
